### ISSUE TITLE
building the workload from a local image

### ISSUE THREAD

**Issue by mahmoodn** [ParsaLab/cloudsuite#20]
I am trying to build the 
docker images locally and in an offline manner. Here is what have done already
**1)** _docker load -i /home/mahmood/cloudsuite_v3/ubuntu.tar_
**2)** _mkdir -p data-analytics/dataset_
**3)** _vim data-analytics/dataset/Dockerfile_
```
FROM ubuntu:10.04
RUN apt-get update && apt-get install wget -y
RUN mkdir /data
RUN cd /data \
  && wget -nv http://parsa.epfl.ch/cloudsuite/software/enwiki-20100904-pages-articles1.xml.bz2
VOLUME ["/data"]
```

**4)** _docker build data-analytics/dataset_
the last lines of a successful build looks like
```
Step 5 : VOLUME /data
 ---> Running in 7d9f2f95c6e8
 ---> 5d0c5e9188d9
Removing intermediate container 7d9f2f95c6e8
Successfully built 5d0c5e9188d9
```

Then, according to the guide, the next command is 
_docker create --name data cloudsuite/data-analytics:dataset_

However, am I not able to run that. Instead, I ran

_docker build -t data-analytics:dataset ./data-analytics/dataset_
```
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu:14.04
 ---> 780bd4494e2f
Step 2 : RUN apt-get update && apt-get install wget -y
 ---> Using cache
 ---> 4418b70655ff
Step 3 : RUN mkdir /data
 ---> Using cache
 ---> 9db3edf4a620
Step 4 : RUN cd /data   && wget -nv http://parsa.epfl.ch/cloudsuite/software/enwiki-20100904-pages-articles1.xml.bz2
 ---> Using cache
 ---> fd44c4dc38ad
Step 5 : VOLUME /data
 ---> Using cache
 ---> 5d0c5e9188d9
Successfully built 5d0c5e9188d9
```

Now, I have to start the master. What are the steps then? The pull command is used for online activities through docker. I want to build it offline from a local image

**Comment by mahmoodn** [comment]
I successfully ran the create command. Now, I have to start the master. Two commands should be used 

_$ docker pull cloudsuite/data-analytics:master
$ docker run -d -t --dns 127.0.0.1 -P --name master -h master.cloudsuite.com --volumes-from data cloudsuite/data-analytics:master_

Instead, I tried

_mahmood@orca:cloudsuite_v3$ mkdir -p data-analytics/master
mahmood@orca:cloudsuite_v3$ vim data-analytics/master/Dockerfile_    (the Dockerfile content is the same as [this](https://github.com/ParsaLab/cloudsuite/blob/master/benchmarks/data-analytics/master/Dockerfile))
_mahmood@orca:cloudsuite_v3$ mkdir -p data-analytics/master
mahmood@orca:cloudsuite_v3$ docker build data-analytics/master
Sending build context to Docker daemon 4.096 kB
Step 1 : FROM cloudsuite/data-analytics:base
Pulling repository docker.io/cloudsuite/data-analytics_

As you can see, it again tries to pull. What should I do?
Also, should I download files and folders of master from the github and move them to my local host?

**Comment by neo-apz** [comment]
The base image (check `FROM` statement) of this image is `data-analytics:base`. So you have to first build that one and try to build `data-analytics:master`.

**Comment by mahmoodn** [comment]
1- FYI, there is no information about building the base/ in the data-analytics guide. 
2- Should I use _build -t_ (similar to the dataset) for all folders? Or that _-t_ is used for only dataset?
3- The serf package from [bintray.com](https://dl.bintray.com/mitchellh/serf/0.5.0_linux_amd64.zip) is no longer available. Is that the same as [serf.googlecode.com]( http://serf.googlecode.com/svn/src_releases)? Please provide us the package to prevent any version mismatch

**Comment by aledaglis** [comment]
First off, I'd like to mention that the vast majority of this thread is about Docker, not CloudSuite. We offer CloudSuite 3.0 with Docker just to ease the process of deploying it. If, for any reason, you want to follow your own setup and not follow the instructions, you'll have to become more familiar with Docker, and this is not something our documentation/support aspires to cover. If this is an overhead you'd prefer to avoid, you can follow the Dockerfiles as instructions for a bare metal setup (w/o Docker).

To answer your Q's:
1- Following what I mentioned above, there is indeed no special information about building the base, as the way you are setting it up is not our intended use case. This means you have to follow the commands in the Dockerfiles on your own. In this particular case, the Dockerfile specifies that the **base** image is required (as implied by the **FROM** keyword).
2- I'm not sure I understand the question. The -t option of the [build](https://docs.docker.com/engine/reference/commandline/build/) command is used to **tag** the image you're building, in order to make it easier to refer to it.
3- Thanks for pointing that out. I opened a separate issue for that to be updated. You can find the package that is used by the Dockerfile [here](https://releases.hashicorp.com/serf/0.5.0/serf_0.5.0_linux_amd64.zip).

**Comment by neo-apz** [comment]
@mahmoodn Take a look at [this](https://groups.google.com/forum/#!topic/software-taak/xRmFWrozRoo). It may help you solving your problem.
